workflows:
  android-workflow:
    name: U-AUBEN INVENTORY - Native Offline Fix
    max_build_duration: 60
    environment:
      java: 21
      node: latest
    scripts:
      - name: Clean & Install Dependencies
        script: |
          # On garde le dossier www mais on nettoie le reste
          rm -rf node_modules package-lock.json android
          
          # Installation des dépendances
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/android lucide marked tailwindcss
          
      - name: Prepare Offline Assets
        script: |
          # 1. On s'assure que les sous-dossiers existent dans www
          mkdir -p www/css www/js
          
          # 2. Compilation de Tailwind CSS
          # On dit à tailwind de scanner le index.html qui est DÉJÀ dans www
          npx tailwindcss -content "./www/index.html" -o www/css/style.css --minify
          
          # 3. Copie physique des bibliothèques JS dans www/js pour l'accès Offline
          cp node_modules/lucide/dist/umd/lucide.min.js www/js/
          cp node_modules/marked/marked.min.js www/js/

      - name: Initialize Android Platform
        script: |
          # On ajoute la plateforme (Capacitor lira le dossier www existant)
          npx cap add android
          npx cap sync android
          
      - name: Patch Gradle & SDK
        script: |
          find android -name "build.gradle" -exec sed -i 's/compileSdk 34/compileSdk 35/g' {} +
          find android -name "build.gradle" -exec sed -i 's/targetSdk 34/targetSdk 35/g' {} +
          
      - name: Build Debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
