workflows:
  android-workflow:
    name: U-AUBEN INVENTORY Build
    max_build_duration: 60
    environment:
      java: 21
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/android @capacitor/core @capacitor/cli
      - name: Clean and Sync
        script: |
          rm -rf android
          npx cap add android
          npx cap sync android
      - name: Build Debug APK (No Keystore needed)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    # On ne met PAS de section 'publishing' ici pour éviter l'erreur
    
