workflows:
  android-workflow:
    name: U-AUBEN INVENTORY - Native Offline Fix
    max_build_duration: 60
    environment:
      java: 21
      node: latest
    scripts:
      - name: Clean & Install Dependencies
        script: |
          # 1. Nettoyage radical pour repartir sur une base saine
          rm -rf node_modules package-lock.json android
          
          # 2. Installation de toutes les dépendances listées
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/android lucide marked tailwindcss
          
      - name: Prepare Offline Assets
        script: |
          # 1. Création de TOUTE la structure de dossiers dans www
          mkdir -p www/css www/js www/fonts
          
          # 2. Compilation de Tailwind CSS (scan du fichier dans www vers le css de www)
          # On s'assure que le design est généré localement
          npx tailwindcss -content "./www/index.html" -o www/css/style.css --minify
          
          # 3. Copie des scripts JS (Lucide et Marked) pour qu'ils soient dans l'APK
          cp node_modules/lucide/dist/umd/lucide.min.js www/js/
          cp node_modules/marked/marked.min.js www/js/
          
          # 4. FORMULE MAGIQUE POUR LES POLICES :
          # On copie tes fichiers .woff2 depuis ton dossier /fonts (racine) vers www/fonts
          # Le "|| true" évite que le build plante si tu as oublié un fichier
          cp fonts/*.woff2 www/fonts/ || true

      - name: Initialize Android Platform
        script: |
          # On force Capacitor à utiliser le dossier www préparé
          npx cap add android
          npx cap sync android
          
      - name: Patch Gradle & SDK
        script: |
          # Mise à jour forcée pour éviter les erreurs de version Android sur Codemagic
          find android -name "build.gradle" -exec sed -i 's/compileSdk 34/compileSdk 35/g' {} +
          find android -name "build.gradle" -exec sed -i 's/targetSdk 34/targetSdk 35/g' {} +
          
      - name: Build Debug APK
        script: |
          # Lancement de la compilation native
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
