workflows:
  android-workflow:
    name: Aube App Final Build - J21
    max_build_duration: 60
    environment:
      java: 21 # On passe enfin sur la version attendue par Capacitor
      node: 20.x
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/android @capacitor/core @capacitor/cli
      - name: Rebuild Android Platform
        script: |
          rm -rf android
          npx cap add android
          npx cap sync android
      - name: Patch SDK for Vanilla Ice Cream
        script: |
          # On garde le SDK 35 car Capacitor en a besoin pour compiler les SystemBars
          find android -name "build.gradle" -exec sed -i '' 's/compileSdk 34/compileSdk 35/g' {} +
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
      
