workflows:
  android-workflow:
    name: U-AUBEN INVENTORY - SQLite Native Build
    max_build_duration: 60
    environment:
      java: 21
      node: latest
    scripts:
      - name: Clean & Install Dependencies
        script: |
          rm -rf node_modules package-lock.json android
          npm install
          npm install @capacitor-community/sqlite @capacitor/cli @capacitor/core @capacitor/android lucide marked tailwindcss
          
      - name: Prepare Offline Assets (Fonts, JS, CSS)
        script: |
          mkdir -p www/css www/js www/fonts
          
          # Téléchargement des polices
          curl -L -o www/fonts/inter.ttf https://github.com/google/fonts/raw/main/ofl/inter/static/Inter-Regular.ttf
          curl -L -o www/fonts/algerian.ttf https://github.com/google/fonts/raw/main/ofl/cinzel/Cinzel-Bold.ttf
          curl -L -o www/fonts/monotype.ttf https://github.com/google/fonts/raw/main/ofl/dancingscript/DancingScript-VariableFont_wght.ttf

          # GÉNÉRATION TAILWIND AGRESSIVE
          # On passe les fichiers directement en argument pour ignorer les erreurs de config
          npx tailwindcss -content "./www/index.html" -o ./www/css/style.css --minify
          
          # Vérification de la taille du fichier (si 0 octet, le build doit échouer ici)
          if [ ! -s ./www/css/style.css ]; then echo "ERREUR : style.css est vide !"; exit 1; fi

          cp node_modules/lucide/dist/umd/lucide.min.js www/js/
          cp node_modules/marked/marked.min.js www/js/

      - name: Initialize Android Platform
        script: |
          npx cap add android
          # On force la copie des fichiers Web vers Android AVANT la synchro
          npx cap copy android
          npx cap sync android
          
      - name: Patch Gradle & SDK
        script: |
          perl -i -pe 's/compileSdk 34/compileSdk 35/g' android/app/build.gradle
          perl -i -pe 's/targetSdk 34/targetSdk 35/g' android/app/build.gradle
          perl -i -pe 's/compileSdk 34/compileSdk 35/g' android/build.gradle
          
      - name: Build Debug APK
        script: |
          # Ultime synchro pour être CERTAIN que le style.css est dans l'APK
          npx cap copy android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
      
