workflows:
  android-workflow:
    name: U-AUBEN INVENTORY APP Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.uauben.inventory"
      node: v20.11.0
      java: 21
      
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          
      - name: Install dependencies
        script: |
          npm install
          
      - name: Download assets
        script: |
          npm run copy-assets
          
      - name: Setup Capacitor
        script: |
          npx cap sync android
          
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
      
    publishing:
      email:
        recipients:
          - dev@uauben.com
        notify:
          success: true
          failure: true
