workflows:
  android-workflow:
    name: Aube App Build Success
    max_build_duration: 60
    environment:
      java: 21
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/android @capacitor/core @capacitor/cli
      - name: Clean and Rebuild Platform
        script: |
          # On s'assure de repartir à zéro
          rm -rf android
          npx cap add android
          npx cap sync android
      - name: Patch SDK and Vanilla Ice Cream
        script: |
          # Correction du SDK pour Capacitor 6+
          find android -name "build.gradle" -exec sed -i '' 's/compileSdk 34/compileSdk 35/g' {} +
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
      
