workflows:
  android-workflow:
    name: U-AUBEN INVENTORY - SQLite Native Build
    max_build_duration: 60
    environment:
      java: 21
      node: latest
    scripts:
      - name: Clean & Install Dependencies
        script: |
          rm -rf node_modules package-lock.json android
          npm install
          npm install @capacitor-community/sqlite @capacitor/cli @capacitor/core @capacitor/android lucide marked tailwindcss
          
      - name: Prepare Offline Assets (Fonts, JS, CSS)
        script: |
          mkdir -p www/css www/js www/fonts
          
          # Téléchargement des polices
          curl -L -o www/fonts/inter.ttf https://github.com/google/fonts/raw/main/ofl/inter/static/Inter-Regular.ttf
          curl -L -o www/fonts/algerian.ttf https://github.com/google/fonts/raw/main/ofl/cinzel/Cinzel-Bold.ttf
          curl -L -o www/fonts/monotype.ttf https://github.com/google/fonts/raw/main/ofl/dancingscript/DancingScript-VariableFont_wght.ttf

          # 1. LA SOLUTION : Création du fichier source contenant les directives Tailwind obligatoires
          echo "@tailwind base;" > tailwind-input.css
          echo "@tailwind components;" >> tailwind-input.css
          echo "@tailwind utilities;" >> tailwind-input.css

          # 2. GÉNÉRATION TAILWIND (Utilisation de -i pour l'entrée et -o pour la sortie)
          npx tailwindcss -i tailwind-input.css -o ./www/css/style.css --content "./www/index.html" --minify
          
          # Copie des scripts JS
          cp node_modules/lucide/dist/umd/lucide.min.js www/js/
          cp node_modules/marked/marked.min.js www/js/

      - name: Initialize Android Platform
        script: |
          npx cap add android
          npx cap copy android
          npx cap sync android
          
      - name: Patch Gradle & SDK
        script: |
          perl -i -pe 's/compileSdk 34/compileSdk 35/g' android/app/build.gradle
          perl -i -pe 's/targetSdk 34/targetSdk 35/g' android/app/build.gradle
          perl -i -pe 's/compileSdk 34/compileSdk 35/g' android/build.gradle
          
      - name: Build Debug APK
        script: |
          npx cap copy android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
      
