workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      java: 17
      node: 24.13.0
    scripts:
      - name: Set Java 17
        script: |
          export JAVA_HOME=$JAVA_HOME_17
          echo "Java version:"
          java -version
      - name: Install dependencies
        script: |
          npm install
      - name: Capacitor Sync
        script: |
          npx cap sync
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
