workflows:
  android-workflow:
    name: Aube App Final Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/android @capacitor/core @capacitor/cli
      - name: Rebuild Android Platform
        script: |
          rm -rf android
          npx cap add android
          npx cap sync android
      - name: Force Java 17 and SDK 35 (Deep Patch)
        script: |
          # 1. Créer un gradle.properties global pour forcer le JDK
          echo "org.gradle.java.home=$JAVA_HOME_17" >> android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

          # 2. Forcer le SDK 35 (pour l'erreur VANILLA_ICE_CREAM)
          find android -name "build.gradle" -exec sed -i '' 's/compileSdk 34/compileSdk 35/g' {} +
          find android -name "build.gradle" -exec sed -i '' 's/targetSdk 34/targetSdk 34/g' {} +
          
          # 3. Écraser TOUTE mention de Java 21 par Java 17
          find android -name "build.gradle" -exec sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' {} +
          find android -name "build.gradle" -exec sed -i '' 's/sourceCompatibility 21/sourceCompatibility 17/g' {} +
          find android -name "build.gradle" -exec sed -i '' 's/targetCompatibility 21/targetCompatibility 17/g' {} +
          find android -name "build.gradle" -exec sed -i '' 's/sourceCompatibility = 21/sourceCompatibility = 17/g' {} +
          find android -name "build.gradle" -exec sed -i '' 's/targetCompatibility = 21/targetCompatibility = 17/g' {} +

      - name: Build Android APK
        script: |
          export JAVA_HOME=$JAVA_HOME_17
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
      
