workflows:
  android-workflow:
    name: Aube App Final Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/android @capacitor/core @capacitor/cli
      - name: Rebuild Android Platform
        script: |
          # Suppression de sécurité si le dossier existe encore
          rm -rf android
          # Création et synchronisation
          npx cap add android
          npx cap sync android
      - name: Patch Gradle for Java 17/SDK 35
        script: |
          # Correction des versions de SDK dans le fichier généré
          sed -i '' 's/compileSdk 34/compileSdk 35/g' android/app/build.gradle
          sed -i '' 's/minSdkVersion 22/minSdkVersion 24/g' android/app/build.gradle
      - name: Build Android APK
        script: |
          export JAVA_HOME=$JAVA_HOME_17
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
      
